# 第一階段-建置編譯環境&把專案編譯成Web服務
FROM ubuntu:latest AS build-env
# 時區
ENV TZ=Asia/Taipei
RUN echo "${TZ}" > /etc/timezone 
RUN ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
# 1-1 安裝 flutter 相依套件
RUN apt-get update
RUN apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3 sed
RUN apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
RUN apt-get clean
# 1-2 從源碼倉庫抓取源碼
RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter
# 1-3 設置flutter預設路徑
ENV PATH="${PATH}:/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin"
# 1-4 Run flutter doctor
RUN flutter doctor -v
RUN flutter channel stable
RUN flutter upgrade
# 1-5 復制專案到容器且開始編譯
RUN mkdir /app/
COPY . /app/
WORKDIR /app/
RUN flutter clean
RUN flutter pub get
RUN flutter build web

# 第二階段-建立提供實時運作的服務
FROM nginx:alpine 
# 2-0 復制編譯好的檔案
COPY --from=build-env /app/build/web /usr/share/nginx/html
# 2-1 時區
ENV TZ=Asia/Taipei
RUN echo "${TZ}" > /etc/timezone 
RUN ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime 
# 2-2 連結埠
EXPOSE 80