# 第一階段-建置編譯環境
FROM ghcr.io/cirruslabs/flutter:stable AS build-env

# 設置時區
ENV TZ=Asia/Taipei
RUN echo "${TZ}" > /etc/timezone && \
    ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime

# 建立相關目錄
RUN mkdir /app
COPY . /app
WORKDIR /app

# 清理、安裝依賴的函式庫並進行 Web 應用編譯
RUN flutter clean && \
    flutter pub get && \
    flutter build web

# 第二階段-建立提供實時運作的服務
FROM nginx:alpine

# 復制編譯好的二進制檔案到 Nginx 服務目錄
COPY --from=build-env /app/build/web /usr/share/nginx/html

# 設置時區
ENV TZ=Asia/Taipei
RUN echo "${TZ}" > /etc/timezone && \
    ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime

# 開放對外連結的通訊埠 & Http Server
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
